function animateAStarRoute( ...
    figureHandle,axesHandle,searchHistory, ...
    finalPath,cfg)
%ANIMATEASTARROUTE Animate A* search and the final route.
%
% Visual sequence:
% 1. Blue/cyan A* search-tree expansion.
% 2. Bright green final route revealed progressively.
% 3. Temporary animation graphics are deleted.
%
% This function changes no navigation state or planner result.

if ~cfg.path.animation.enabled
    return;
end

if isempty(searchHistory.expandedWorld) || ...
        isempty(finalPath)
    return;
end

if isempty(figureHandle) || ...
        ~ishandle(figureHandle) || ...
        ~strcmpi(get(figureHandle,'Type'),'figure')
    error('A valid figure handle is required for A* animation.');
end

if isempty(axesHandle) || ...
        ~ishandle(axesHandle) || ...
        ~strcmpi(get(axesHandle,'Type'),'axes')
    error('A valid axes handle is required for A* animation.');
end

set(0,'CurrentFigure',figureHandle);
set(figureHandle,'CurrentAxes',axesHandle);
hold(axesHandle,'on');

treeHandle = plot( ...
    axesHandle,nan,nan, ...
    'Color',[0.10 0.42 0.95], ...
    'LineWidth',0.40);

nodeHandle = plot( ...
    axesHandle,nan,nan,'.', ...
    'Color',[0.08 0.75 1.00], ...
    'MarkerSize',5);

routeHandle = plot( ...
    axesHandle,nan,nan, ...
    'Color',[0.05 0.90 0.25], ...
    'LineWidth',3.0);

startHandle = plot( ...
    axesHandle, ...
    searchHistory.startPoint(1), ...
    searchHistory.startPoint(2), ...
    'go','MarkerFaceColor','g', ...
    'MarkerSize',9,'LineWidth',1.5);

goalHandle = plot( ...
    axesHandle, ...
    searchHistory.goalPoint(1), ...
    searchHistory.goalPoint(2), ...
    'm*','MarkerSize',17, ...
    'LineWidth',2.0);

statusHandle = text( ...
    axesHandle, ...
    0.50*cfg.environment.worldWidth, ...
    cfg.environment.worldHeight-0.35, ...
    'A* Search Animation: exploring the occupancy grid...', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'Color',[0.02 0.25 0.70], ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.65 0.65 0.65], ...
    'Margin',5);

videoObject = [];
temporaryImage = '';
targetFrameSize = [];

if cfg.path.animation.recordVideo
    videoObject = VideoWriter( ...
        fullfile(cfg.output.resultsFolder, ...
        'astar_route_animation.avi'), ...
        'Motion JPEG AVI');

    videoObject.FrameRate = ...
        cfg.path.animation.frameRate;

    open(videoObject);
    temporaryImage = [tempname '.png'];
end

numberOfExpandedNodes = ...
    size(searchHistory.expandedWorld,1);

edgeX = nan(1,3*numberOfExpandedNodes);
edgeY = nan(1,3*numberOfExpandedNodes);
nodeX = nan(numberOfExpandedNodes,1);
nodeY = nan(numberOfExpandedNodes,1);

try
    for nodeIndex = 1:numberOfExpandedNodes
        nodePoint = ...
            searchHistory.expandedWorld(nodeIndex,:);
        parentPoint = ...
            searchHistory.parentWorld(nodeIndex,:);

        nodeX(nodeIndex) = nodePoint(1);
        nodeY(nodeIndex) = nodePoint(2);

        edgeDataIndex = 3*(nodeIndex-1)+1;

        if all(isfinite(parentPoint))
            edgeX(edgeDataIndex:edgeDataIndex+2) = [ ...
                parentPoint(1),nodePoint(1),nan];

            edgeY(edgeDataIndex:edgeDataIndex+2) = [ ...
                parentPoint(2),nodePoint(2),nan];
        end

        shouldRefresh = ...
            mod(nodeIndex, ...
            cfg.path.animation.explorationStride) == 0 || ...
            nodeIndex == numberOfExpandedNodes;

        if shouldRefresh
            set(treeHandle, ...
                'XData',edgeX(1:3*nodeIndex), ...
                'YData',edgeY(1:3*nodeIndex));

            set(nodeHandle, ...
                'XData',nodeX(1:nodeIndex), ...
                'YData',nodeY(1:nodeIndex));

            set(statusHandle,'String',sprintf( ...
                'A* Search Animation: explored %d of %d nodes', ...
                nodeIndex,numberOfExpandedNodes));

            drawnow;

            if cfg.path.animation.recordVideo
                [targetFrameSize,videoObject] = ...
                    writeAnimationFrameLocal( ...
                    figureHandle,temporaryImage, ...
                    targetFrameSize,videoObject);
            end
        end
    end

    set(statusHandle, ...
        'String','A* Goal Found — revealing final route...', ...
        'Color',[0 0.50 0.10]);

    numberOfRoutePoints = size(finalPath,1);

    routeIndices = unique(round(linspace( ...
        2,numberOfRoutePoints, ...
        min(numberOfRoutePoints, ...
        cfg.path.animation.routeRevealFrames))));

    for revealIndex = routeIndices
        set(routeHandle, ...
            'XData',finalPath(1:revealIndex,1), ...
            'YData',finalPath(1:revealIndex,2));

        drawnow;

        if cfg.path.animation.recordVideo
            [targetFrameSize,videoObject] = ...
                writeAnimationFrameLocal( ...
                figureHandle,temporaryImage, ...
                targetFrameSize,videoObject);
        end
    end

    set(statusHandle,'String',sprintf( ...
        'A* Route Ready — %.2f m, %d expanded nodes', ...
        sum(sqrt(sum(diff(finalPath,1,1).^2,2))), ...
        numberOfExpandedNodes));

    holdFrameCount = max(1,round( ...
        cfg.path.animation.holdSeconds* ...
        cfg.path.animation.frameRate));

    for frameIndex = 1:holdFrameCount
        drawnow;

        if cfg.path.animation.recordVideo
            [targetFrameSize,videoObject] = ...
                writeAnimationFrameLocal( ...
                figureHandle,temporaryImage, ...
                targetFrameSize,videoObject);
        else
            pause(1/cfg.path.animation.frameRate);
        end
    end

    if cfg.path.animation.recordVideo
        close(videoObject);
    end
catch errorInformation
    if cfg.path.animation.recordVideo
        try
            close(videoObject);
        catch
        end
    end

    if ~isempty(temporaryImage) && ...
            exist(temporaryImage,'file')
        delete(temporaryImage);
    end

    safeDeleteLocal(treeHandle);
    safeDeleteLocal(nodeHandle);
    safeDeleteLocal(routeHandle);
    safeDeleteLocal(startHandle);
    safeDeleteLocal(goalHandle);
    safeDeleteLocal(statusHandle);

    rethrow(errorInformation);
end

if ~isempty(temporaryImage) && ...
        exist(temporaryImage,'file')
    delete(temporaryImage);
end

% Remove only the temporary animation overlay. The existing simulation
% graphics and all navigation variables remain unchanged.
safeDeleteLocal(treeHandle);
safeDeleteLocal(nodeHandle);
safeDeleteLocal(routeHandle);
safeDeleteLocal(startHandle);
safeDeleteLocal(goalHandle);
safeDeleteLocal(statusHandle);

drawnow;
end

function [targetFrameSize,videoObject] = ...
    writeAnimationFrameLocal( ...
    figureHandle,temporaryImage, ...
    targetFrameSize,videoObject)

rgbFrame = utilities( ...
    'captureFigureRGB', ...
    figureHandle,temporaryImage);

if isempty(targetFrameSize)
    frameHeight = size(rgbFrame,1)- ...
        mod(size(rgbFrame,1),2);

    frameWidth = size(rgbFrame,2)- ...
        mod(size(rgbFrame,2),2);

    targetFrameSize = [frameHeight frameWidth];
end

rgbFrame = utilities( ...
    'fitFrame',rgbFrame,targetFrameSize);

writeVideo(videoObject,rgbFrame);
end

function safeDeleteLocal(handleValue)

try
    if ~isempty(handleValue) && ...
            ishandle(handleValue)
        delete(handleValue);
    end
catch
end
end
