function robotHandles = drawRobot( ...
    axesHandle,pose,cfg,robotHandles)
%DRAWROBOT Draw or update a realistic differential-drive robot.
%
% Visual components:
% - circular body,
% - left wheel,
% - right wheel,
% - heading arrow,
% - robot center marker.

if nargin < 4
    robotHandles = [];
end

bodyAngles = linspace(0,2*pi,50);
bodyX = pose(1)+cfg.robot.radius*cos(bodyAngles);
bodyY = pose(2)+cfg.robot.radius*sin(bodyAngles);

[leftWheelX,leftWheelY] = wheelPolygon( ...
    pose,+1,cfg);

[rightWheelX,rightWheelY] = wheelPolygon( ...
    pose,-1,cfg);

headingEnd = pose(1:2)+ ...
    cfg.robot.headingArrowLength* ...
    [cos(pose(3));sin(pose(3))];

if isempty(robotHandles) || ...
        ~isfield(robotHandles,'body') || ...
        ~ishandle(robotHandles.body)

    hold(axesHandle,'on');

    robotHandles.body = patch( ...
        axesHandle,bodyX,bodyY, ...
        cfg.visualization.robotBodyColor, ...
        'EdgeColor','k','LineWidth',1.7);

    robotHandles.leftWheel = patch( ...
        axesHandle,leftWheelX,leftWheelY, ...
        cfg.visualization.wheelColor, ...
        'EdgeColor','k','LineWidth',1.0);

    robotHandles.rightWheel = patch( ...
        axesHandle,rightWheelX,rightWheelY, ...
        cfg.visualization.wheelColor, ...
        'EdgeColor','k','LineWidth',1.0);

    robotHandles.heading = plot( ...
        axesHandle, ...
        [pose(1) headingEnd(1)], ...
        [pose(2) headingEnd(2)], ...
        'Color',cfg.visualization.headingColor, ...
        'LineWidth',2.5);

    robotHandles.center = plot( ...
        axesHandle,pose(1),pose(2),'ko', ...
        'MarkerFaceColor','w', ...
        'MarkerSize',5);
else
    set(robotHandles.body, ...
        'XData',bodyX,'YData',bodyY);

    set(robotHandles.leftWheel, ...
        'XData',leftWheelX,'YData',leftWheelY);

    set(robotHandles.rightWheel, ...
        'XData',rightWheelX,'YData',rightWheelY);

    set(robotHandles.heading, ...
        'XData',[pose(1) headingEnd(1)], ...
        'YData',[pose(2) headingEnd(2)]);

    set(robotHandles.center, ...
        'XData',pose(1),'YData',pose(2));
end
end

function [worldX,worldY] = wheelPolygon( ...
    pose,sideSign,cfg)

wheelLength = cfg.robot.wheelLength;
wheelWidth = cfg.robot.wheelWidth;

localCenter = [ ...
    0;sideSign*cfg.robot.wheelBase/2];

localCorners = [ ...
     wheelLength/2,  wheelWidth/2;
     wheelLength/2, -wheelWidth/2;
    -wheelLength/2, -wheelWidth/2;
    -wheelLength/2,  wheelWidth/2]';

rotation = [ ...
    cos(pose(3)) -sin(pose(3));
    sin(pose(3))  cos(pose(3))];

worldCorners = rotation*( ...
    localCorners+localCenter)+pose(1:2);

worldX = worldCorners(1,:);
worldY = worldCorners(2,:);
end
