function [bestCommand,bestTrajectory,debug] = ...
    dynamicWindowApproach( ...
    pose,currentCommand,goal,scan, ...
    recoveryState,cfg)
%DYNAMICWINDOWAPPROACH Complete local DWA implementation.
%
% DWA generates dynamically reachable linear/angular velocity candidates,
% predicts each candidate trajectory, rejects unsafe trajectories, and
% scores valid candidates using:
% - heading toward the clicked goal,
% - direct progress toward the goal,
% - obstacle clearance from current LiDAR points,
% - forward velocity,
% - stopping-distance safety,
% - smooth steering,
% - local-minimum recovery preference.
%
% The supplied goal is the current continuous path look-ahead target.

timeStep = cfg.simulation.timeStep;

%% Dynamic velocity window
minimumReachableVelocity = max( ...
    cfg.robot.minimumLinearVelocity, ...
    currentCommand(1)- ...
    cfg.robot.maximumLinearDeceleration*timeStep);

maximumReachableVelocity = min( ...
    cfg.robot.maximumLinearVelocity, ...
    currentCommand(1)+ ...
    cfg.robot.maximumLinearAcceleration*timeStep);

% If a path corner temporarily lowers the speed limit below the current
% speed, preserve a physically reachable deceleration window.
maximumReachableVelocity = max( ...
    minimumReachableVelocity,maximumReachableVelocity);

minimumReachableTurnRate = max( ...
    -cfg.robot.maximumAngularVelocity, ...
    currentCommand(2)- ...
    cfg.robot.maximumAngularAcceleration*timeStep);

maximumReachableTurnRate = min( ...
    cfg.robot.maximumAngularVelocity, ...
    currentCommand(2)+ ...
    cfg.robot.maximumAngularAcceleration*timeStep);

distanceToGoal = norm(pose(1:2)'-goal);

if distanceToGoal < cfg.goal.slowingRadius
    maximumReachableVelocity = max( ...
        minimumReachableVelocity, ...
        min(maximumReachableVelocity, ...
        max(0.05,cfg.goal.approachGain* ...
        distanceToGoal)));
end

clampedCurrentVelocity = utilities( ...
    'clamp',currentCommand(1), ...
    minimumReachableVelocity, ...
    maximumReachableVelocity);

clampedCurrentTurnRate = utilities( ...
    'clamp',currentCommand(2), ...
    minimumReachableTurnRate, ...
    maximumReachableTurnRate);

linearVelocityCandidates = unique([ ...
    linspace(minimumReachableVelocity, ...
    maximumReachableVelocity, ...
    cfg.dwa.linearVelocitySamples), ...
    0,clampedCurrentVelocity]);

angularVelocityCandidates = unique([ ...
    linspace(minimumReachableTurnRate, ...
    maximumReachableTurnRate, ...
    cfg.dwa.angularVelocitySamples), ...
    0,clampedCurrentTurnRate]);

obstaclePoints = scan.hitPoints( ...
    scan.hitMask,:);

bestScore = -inf;
bestCommand = [0;0];
bestTrajectory = pose';
bestEvaluation = struct();
validCandidateCount = 0;

for linearIndex = 1:numel( ...
        linearVelocityCandidates)
    candidateLinearVelocity = ...
        linearVelocityCandidates(linearIndex);

    for angularIndex = 1:numel( ...
            angularVelocityCandidates)
        candidateAngularVelocity = ...
            angularVelocityCandidates(angularIndex);

        candidateCommand = [ ...
            candidateLinearVelocity;
            candidateAngularVelocity];

        candidateTrajectory = ...
            predictTrajectory( ...
            pose,candidateCommand,cfg);

        [score,evaluation,isSafe] = ...
            evaluateTrajectory( ...
            candidateTrajectory,candidateCommand, ...
            currentCommand,goal,obstaclePoints, ...
            recoveryState,cfg);

        if ~isSafe
            continue;
        end

        validCandidateCount = ...
            validCandidateCount+1;

        if score > bestScore
            bestScore = score;
            bestCommand = candidateCommand;
            bestTrajectory = candidateTrajectory;
            bestEvaluation = evaluation;
        end
    end
end

%% Safe local recovery when all sampled forward trajectories are invalid
frontOpening = mean(scan.ranges( ...
    abs(scan.localAngles) < 35*pi/180));

leftOpening = mean(scan.ranges( ...
    scan.localAngles > 20*pi/180 & ...
    scan.localAngles < 150*pi/180));

rightOpening = mean(scan.ranges( ...
    scan.localAngles < -20*pi/180 & ...
    scan.localAngles > -150*pi/180));

if validCandidateCount == 0 || ...
        ~isfinite(bestScore)

    if leftOpening >= rightOpening
        turnDirection = 1;
    else
        turnDirection = -1;
    end

    bestCommand = [ ...
        0;
        turnDirection*min( ...
        cfg.safety.emergencyTurnRate, ...
        cfg.robot.maximumAngularVelocity)];

    bestTrajectory = predictTrajectory( ...
        pose,bestCommand,cfg);

    bestScore = -1;
    bestEvaluation.minimumClearance = ...
        min(scan.ranges);
    bestEvaluation.progressScore = 0;
end

debug.bestScore = bestScore;
debug.validCandidateCount = validCandidateCount;
debug.minimumClearance = ...
    bestEvaluation.minimumClearance;
debug.progressScore = ...
    bestEvaluation.progressScore;
debug.openingFront = frontOpening;
debug.openingLeft = leftOpening;
debug.openingRight = rightOpening;
debug.recoveryActive = recoveryState.active;
end

function trajectory = predictTrajectory( ...
    initialPose,command,cfg)

predictionSteps = max(1,ceil( ...
    cfg.dwa.predictionTime/ ...
    cfg.dwa.predictionTimeStep));

trajectory = zeros(predictionSteps+1,3);
trajectory(1,:) = initialPose';

pose = initialPose;

for step = 1:predictionSteps
    pose = robotKinematics( ...
        pose,command, ...
        cfg.dwa.predictionTimeStep);

    trajectory(step+1,:) = pose';
end
end
