function [totalScore,evaluation,isSafe] = ...
    evaluateTrajectory( ...
    trajectory,candidateCommand,currentCommand, ...
    goal,obstaclePoints,recoveryState,cfg)
%EVALUATETRAJECTORY Score one DWA trajectory and enforce safety.
%
% The function uses only the currently observed LiDAR point cloud and the
% clicked goal. It contains no global route or waypoint information.

trajectoryPositions = trajectory(:,1:2);

initialGoalDistance = norm( ...
    trajectoryPositions(1,:)-goal);

finalGoalDistance = norm( ...
    trajectoryPositions(end,:)-goal);

goalDirection = atan2( ...
    goal(2)-trajectory(end,2), ...
    goal(1)-trajectory(end,1));

headingError = utilities( ...
    'wrapAngle', ...
    goalDirection-trajectory(end,3));

headingScore = ...
    0.5*(cos(headingError)+1);

maximumPossibleProgress = ...
    max(cfg.robot.maximumLinearVelocity* ...
    cfg.dwa.predictionTime,eps);

progressAmount = ...
    initialGoalDistance-finalGoalDistance;

progressScore = utilities( ...
    'clamp', ...
    0.5+0.5*progressAmount/ ...
    maximumPossibleProgress,0,1);

goalProximityScore = utilities( ...
    'clamp', ...
    1-finalGoalDistance/ ...
    max(initialGoalDistance,eps),0,1);

velocityScore = utilities( ...
    'clamp', ...
    candidateCommand(1)/ ...
    max(cfg.robot.maximumLinearVelocity,eps), ...
    0,1);

linearChange = abs( ...
    candidateCommand(1)-currentCommand(1)) / ...
    max(cfg.robot.maximumLinearAcceleration* ...
    cfg.simulation.timeStep,eps);

angularChange = abs( ...
    candidateCommand(2)-currentCommand(2)) / ...
    max(cfg.robot.maximumAngularAcceleration* ...
    cfg.simulation.timeStep,eps);

smoothnessScore = exp( ...
    -0.7*linearChange^2- ...
    0.45*angularChange^2);

steeringScore = ...
    1-utilities('clamp', ...
    abs(candidateCommand(2))/ ...
    max(cfg.robot.maximumAngularVelocity,eps), ...
    0,1);

%% Obstacle clearance from current LiDAR hit points
if isempty(obstaclePoints)
    minimumCenterDistance = ...
        cfg.lidar.maximumRange;
else
    minimumCenterDistance = inf;

    for trajectoryIndex = 1:size( ...
            trajectoryPositions,1)
        position = ...
            trajectoryPositions(trajectoryIndex,:);

        pointDistances = sqrt(sum( ...
            (obstaclePoints-position).^2,2));

        minimumCenterDistance = min( ...
            minimumCenterDistance, ...
            min(pointDistances));
    end
end

surfaceClearance = ...
    minimumCenterDistance-cfg.robot.radius;

clearanceScore = utilities( ...
    'clamp', ...
    surfaceClearance/ ...
    max(cfg.lidar.maximumRange- ...
    cfg.robot.radius,eps), ...
    0,1);

%% Safe stopping-distance constraint
stoppingDistance = ...
    candidateCommand(1)^2 / ...
    (2*max(cfg.robot.maximumLinearDeceleration,eps)) + ...
    candidateCommand(1)*cfg.dwa.reactionTime + ...
    cfg.safety.clearanceBuffer;

requiredCenterDistance = ...
    cfg.robot.radius+stoppingDistance;

brakingMargin = ...
    minimumCenterDistance-requiredCenterDistance;

brakingScore = utilities( ...
    'clamp', ...
    brakingMargin/ ...
    max(cfg.dwa.stoppingScoreScale,eps), ...
    0,1);

isSafe = minimumCenterDistance > ...
    cfg.robot.radius+ ...
    cfg.safety.minimumGeometricClearance;

% High-speed candidates must also satisfy stopping distance.
if candidateCommand(1) > ...
        cfg.dwa.lowSpeedSafetyThreshold
    isSafe = isSafe && brakingMargin > 0;
end

%% Keep predicted robot center inside world bounds
insideWorld = all( ...
    trajectoryPositions(:,1) > ...
    cfg.robot.radius & ...
    trajectoryPositions(:,1) < ...
    cfg.environment.worldWidth- ...
    cfg.robot.radius & ...
    trajectoryPositions(:,2) > ...
    cfg.robot.radius & ...
    trajectoryPositions(:,2) < ...
    cfg.environment.worldHeight- ...
    cfg.robot.radius);

% Route-lock safety is evaluated later, after the predicted trajectory
% has been compared with the A* reference path.
isSafe = isSafe && insideWorld;

%% Recovery-mode local exploration bias
recoveryScore = 0.5;

if recoveryState.active
    preferredSign = ...
        recoveryState.preferredTurnDirection;

    if sign(candidateCommand(2)) == ...
            preferredSign && ...
            abs(candidateCommand(2)) > ...
            cfg.recovery.minimumTurnRate
        recoveryScore = 1;
    elseif candidateCommand(1) > ...
            cfg.recovery.maximumRecoveryVelocity
        recoveryScore = 0;
    end
end


%% Full predicted-trajectory path tracking score
pathTrackingScore = 0;
pathHeadingScore = 0;
pathProgressScore = 0;
predictedPathRMSE = inf;
predictedMaximumPathDeviation = inf;
predictedFinalPathDeviation = inf;
routeLockSafe = true;

if isfield(cfg,'path') && ...
        isfield(cfg.path,'guidanceActive') && ...
        cfg.path.guidanceActive

    referencePath = cfg.path.referencePath;

    if ~isempty(referencePath)
        trajectoryDistanceSquared = zeros( ...
            size(trajectoryPositions,1),1);

        for trajectoryIndex = 1:size(trajectoryPositions,1)
            position = trajectoryPositions(trajectoryIndex,:);

            referenceDistancesSquared = sum( ...
                (referencePath-position).^2,2);

            trajectoryDistanceSquared(trajectoryIndex) = ...
                min(referenceDistancesSquared);
        end

        predictedPathRMSE = sqrt(mean(trajectoryDistanceSquared));
        predictedMaximumPathDeviation = ...
            sqrt(max(trajectoryDistanceSquared));
        predictedFinalPathDeviation = ...
            sqrt(trajectoryDistanceSquared(end));

        pathTrackingScore = exp( ...
            -(predictedPathRMSE/ ...
            max(cfg.path.trackingSigma,eps))^2);

        % Route lock: the A* route is already safety-inflated, so the
        % local planner should not abandon it. When the robot is already
        % outside the normal corridor, only trajectories that do not make
        % the final deviation worse are accepted.
        if cfg.path.routeLockEnabled
            allowedDeviation = max( ...
                cfg.path.maximumPredictionDeviation, ...
                cfg.path.currentCrossTrackError+ ...
                cfg.path.routeLockRecoveryMargin);

            routeLockSafe = ...
                predictedMaximumPathDeviation <= allowedDeviation;

            if cfg.path.currentCrossTrackError > ...
                    cfg.path.maximumPredictionDeviation
                routeLockSafe = routeLockSafe && ...
                    predictedFinalPathDeviation <= ...
                    cfg.path.currentCrossTrackError+ ...
                    cfg.path.maximumFinalDeviationGrowth;
            end
        end
    end

    referenceTangent = cfg.path.referenceTangent;
    tangentNorm = norm(referenceTangent);

    if tangentNorm > eps
        referenceTangent = referenceTangent/tangentNorm;
    else
        referenceTangent = [1 0];
    end

    referenceHeading = atan2( ...
        referenceTangent(2),referenceTangent(1));

    headingDifference = utilities( ...
        'wrapAngle',trajectory(end,3)-referenceHeading);

    pathHeadingScore = 0.5*(cos(headingDifference)+1);

    initialTargetDistance = norm( ...
        trajectoryPositions(1,:)- ...
        cfg.path.referenceProgressPoint);

    finalTargetDistance = norm( ...
        trajectoryPositions(end,:)- ...
        cfg.path.referenceProgressPoint);

    pathProgressScore = utilities( ...
        'clamp', ...
        0.5+0.5*(initialTargetDistance-finalTargetDistance)/ ...
        max(cfg.robot.maximumLinearVelocity* ...
        cfg.dwa.predictionTime,eps),0,1);
end

% Apply route-lock rejection only after routeLockSafe has been
% initialized and calculated from the full predicted trajectory.
isSafe = isSafe && routeLockSafe;

%% Adaptive DWA weights
weights = cfg.dwa.weights;

if recoveryState.active
    weights.heading = ...
        cfg.recovery.weights.heading;
    weights.progress = ...
        cfg.recovery.weights.progress;
    weights.clearance = ...
        cfg.recovery.weights.clearance;
    weights.velocity = ...
        cfg.recovery.weights.velocity;
    weights.smoothness = ...
        cfg.recovery.weights.smoothness;
    weights.braking = ...
        cfg.recovery.weights.braking;
    weights.goalProximity = ...
        cfg.recovery.weights.goalProximity;
    weights.recovery = ...
        cfg.recovery.weights.recovery;
end

totalScore = ...
    weights.heading*headingScore + ...
    weights.progress*progressScore + ...
    weights.clearance*clearanceScore + ...
    weights.velocity*velocityScore + ...
    weights.smoothness*smoothnessScore + ...
    weights.steering*steeringScore + ...
    weights.braking*brakingScore + ...
    weights.goalProximity*goalProximityScore + ...
    weights.recovery*recoveryScore + ...
    cfg.path.trackingWeight*pathTrackingScore + ...
    cfg.path.headingTrackingWeight*pathHeadingScore + ...
    cfg.path.progressTrackingWeight*pathProgressScore;

% Near the goal, strongly prefer trajectories that finish close and slow.
if initialGoalDistance < cfg.goal.slowingRadius
    terminalSpeedScore = ...
        1-utilities('clamp', ...
        candidateCommand(1)/ ...
        max(cfg.robot.maximumLinearVelocity,eps), ...
        0,1);

    totalScore = totalScore + ...
        cfg.goal.terminalDistanceWeight* ...
        goalProximityScore + ...
        cfg.goal.terminalSpeedWeight* ...
        terminalSpeedScore;
end

evaluation.headingScore = headingScore;
evaluation.progressScore = progressScore;
evaluation.clearanceScore = clearanceScore;
evaluation.velocityScore = velocityScore;
evaluation.smoothnessScore = smoothnessScore;
evaluation.steeringScore = steeringScore;
evaluation.brakingScore = brakingScore;
evaluation.goalProximityScore = goalProximityScore;
evaluation.recoveryScore = recoveryScore;
evaluation.pathTrackingScore = pathTrackingScore;
evaluation.pathHeadingScore = pathHeadingScore;
evaluation.pathProgressScore = pathProgressScore;
evaluation.predictedPathRMSE = predictedPathRMSE;
evaluation.predictedMaximumPathDeviation = ...
    predictedMaximumPathDeviation;
evaluation.predictedFinalPathDeviation = ...
    predictedFinalPathDeviation;
evaluation.routeLockSafe = routeLockSafe;
evaluation.minimumClearance = ...
    minimumCenterDistance;
evaluation.surfaceClearance = surfaceClearance;
evaluation.stoppingDistance = stoppingDistance;
evaluation.finalGoalDistance = finalGoalDistance;
end
