function exportSlamMap( ...
    slamState,globalPath,goal, ...
    actualTrajectory,goalReached,cfg)
%EXPORTSLAMMAP Save a world-aligned final occupancy map.
%
% The red line is the actual robot trajectory. The destination is shown
% once, as a red star. The raw SLAM endpoint is not drawn as another goal.

figureHandle = figure( ...
    'Color','w', ...
    'Position',[180 100 1050 760], ...
    'Name','SLAM Live Occupancy Map');

axesHandle = axes('Parent',figureHandle);

mapRGB = occupancyRgbLocal(slamState);

image(axesHandle, ...
    [0 cfg.environment.worldWidth], ...
    [0 cfg.environment.worldHeight], ...
    mapRGB);

set(axesHandle,'YDir','normal');
axis(axesHandle,'equal');
axis(axesHandle,[ ...
    0 cfg.environment.worldWidth ...
    0 cfg.environment.worldHeight]);

hold(axesHandle,'on');
grid(axesHandle,'on');
box(axesHandle,'on');

pathHandle = plot( ...
    axesHandle, ...
    globalPath(:,1),globalPath(:,2), ...
    '--','Color',[0.10 0.35 0.95], ...
    'LineWidth',1.5);

if isempty(actualTrajectory)
    displayTrajectory = ...
        slamState.trajectory(:,1:2);
else
    displayTrajectory = ...
        actualTrajectory(:,1:2);
end

if goalReached && ~isempty(displayTrajectory)
    displayTrajectory(end,:) = goal;
end

trajectoryHandle = plot( ...
    axesHandle, ...
    displayTrajectory(:,1), ...
    displayTrajectory(:,2), ...
    'Color',[0.85 0.10 0.10], ...
    'LineWidth',1.8);

goalHandle = plot( ...
    axesHandle,goal(1),goal(2), ...
    'r*','MarkerSize',20, ...
    'LineWidth',2.4);

text(axesHandle, ...
    goal(1)+0.22,goal(2)+0.18, ...
    'GOAL', ...
    'Color','r', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',2);

if ~isempty(displayTrajectory)
    startHandle = plot( ...
        axesHandle, ...
        displayTrajectory(1,1), ...
        displayTrajectory(1,2), ...
        'gs','MarkerFaceColor','g', ...
        'MarkerSize',7);
else
    startHandle = plot( ...
        axesHandle,nan,nan,'gs');
end

title(axesHandle,sprintf( ...
    ['SLAM Live Occupancy Map — Explored %.1f%% ' ...
     '| World-frame aligned'], ...
    100*slamState.exploredFraction), ...
    'FontWeight','bold');

xlabel(axesHandle,'X position (m)');
ylabel(axesHandle,'Y position (m)');

legend(axesHandle, ...
    [pathHandle trajectoryHandle ...
     startHandle goalHandle], ...
    {'A* route','Actual robot trajectory', ...
     'Start','Single selected goal'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal');

print(figureHandle, ...
    fullfile(cfg.output.resultsFolder, ...
    'slam_live_occupancy_map.png'), ...
    '-dpng','-r200');
end

function mapRGB = occupancyRgbLocal(slamState)

probability = slamState.probability;
grayValue = 1-probability;

mapRGB = repmat(grayValue,[1 1 3]);

unknownMask = ~slamState.observed;

for channel = 1:3
    channelData = mapRGB(:,:,channel);
    channelData(unknownMask) = 0.58;
    mapRGB(:,:,channel) = channelData;
end
end
