function goal = goalSelection( ...
    figureHandle,axesHandle,environment,cfg)
%GOALSELECTION Interactive single-click destination selection.
%
% A single axes title is used during goal selection. It is cleared after
% a valid click so it cannot overlap with the live navigation status.

set(figureHandle,'CurrentAxes',axesHandle);

title(axesHandle, ...
    'Click anywhere in the map to select the destination.', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',[0.75 0.05 0.05]);

drawnow;

while true
    [clickedX,clickedY,button] = ginput(1);

    if isempty(clickedX) || isempty(clickedY) || ...
            isempty(button)
        error('Goal selection was cancelled.');
    end

    candidateGoal = [clickedX clickedY];

    insideMap = ...
        clickedX > cfg.robot.radius && ...
        clickedX < environment.worldWidth- ...
        cfg.robot.radius && ...
        clickedY > cfg.robot.radius && ...
        clickedY < environment.worldHeight- ...
        cfg.robot.radius;

    candidatePose = [clickedX;clickedY;0];

    if insideMap && ...
            ~collisionCheck(candidatePose, ...
            environment,cfg)

        goal = candidateGoal;

        plot(axesHandle,goal(1),goal(2), ...
            'r*','MarkerSize',22, ...
            'LineWidth',2.8);

        text(axesHandle, ...
            goal(1)+0.25,goal(2)+0.20, ...
            'GOAL', ...
            'Color','r', ...
            'FontWeight','bold', ...
            'FontSize',11, ...
            'BackgroundColor','w', ...
            'Margin',2);

        % Clear the selection title. The live status label created by
        % visualization.m becomes the only navigation heading.
        title(axesHandle,'');

        drawnow;
        return;
    end

    title(axesHandle, ...
        ['Invalid goal location. ' ...
        'Click another collision-free location.'], ...
        'Color',[0.85 0.05 0.05], ...
        'FontSize',15, ...
        'FontWeight','bold');

    drawnow;
end
end
