function handles = visualization( ...
    mode,figureHandle,axesHandle,environment, ...
    pose,goal,scan,trajectoryHistory,command, ...
    simulationTime,dwaDebug,cfg,varargin)
%VISUALIZATION Professional non-overlapping dashboard.
%
% Layout:
% - Large navigation map on the left
% - Live SLAM occupancy map on the upper-right
% - Navigation/status labels on the lower-right
% - One fixed heading panel across the top
%
% Labels are drawn in dedicated axes, not inside the map boundary, so
% they remain visible and never overlap the map title or one another.

[figureHandle,axesHandle] = ensureContextLocal( ...
    figureHandle,axesHandle,environment,cfg);

switch lower(mode)
    case 'initialize'
        globalPath = varargin{1};
        localTarget = varargin{2};
        pathInfo = varargin{3};
        slamState = varargin{4};

        handles = initializeLocal( ...
            figureHandle,axesHandle,pose,goal,scan, ...
            command,dwaDebug,cfg,globalPath, ...
            localTarget,pathInfo,slamState);

    case 'update'
        handles = varargin{1};
        predictedTrajectory = varargin{2};
        globalPath = varargin{3};
        localTarget = varargin{4};
        pathInfo = varargin{5};
        slamState = varargin{6};

        if ~handlesValidLocal(handles)
            deleteDynamicLocal(handles);

            handles = initializeLocal( ...
                figureHandle,axesHandle,pose,goal,scan, ...
                command,dwaDebug,cfg,globalPath, ...
                localTarget,pathInfo,slamState);
        end

        handles.figure = figureHandle;
        handles.axes = axesHandle;

        handles = updateLocal( ...
            handles,pose,goal,scan,trajectoryHistory, ...
            command,simulationTime,dwaDebug,cfg, ...
            predictedTrajectory,globalPath,localTarget, ...
            pathInfo,slamState,'');

    case 'finalize'
        handles = varargin{1};
        predictedTrajectory = varargin{2};
        globalPath = varargin{3};
        localTarget = varargin{4};
        pathInfo = varargin{5};
        slamState = varargin{6};
        statusMessage = varargin{7};

        if ~handlesValidLocal(handles)
            deleteDynamicLocal(handles);

            handles = initializeLocal( ...
                figureHandle,axesHandle,pose,goal,scan, ...
                command,dwaDebug,cfg,globalPath, ...
                localTarget,pathInfo,slamState);
        end

        handles.figure = figureHandle;
        handles.axes = axesHandle;

        handles = updateLocal( ...
            handles,pose,goal,scan,trajectoryHistory, ...
            command,simulationTime,dwaDebug,cfg, ...
            predictedTrajectory,globalPath,localTarget, ...
            pathInfo,slamState,statusMessage);

    otherwise
        error('Unknown visualization mode: %s',mode);
end
end

function [figureHandle,axesHandle] = ensureContextLocal( ...
    figureHandle,axesHandle,environment,cfg)

if ~validHandleLocal(figureHandle,'figure')
    figureHandle = figure( ...
        'Name','Hybrid A* + DWA + SLAM Navigation', ...
        'Color','w', ...
        'Position',[25 35 1580 900], ...
        'NumberTitle','off');
end

if ~validHandleLocal(axesHandle,'axes')
    set(0,'CurrentFigure',figureHandle);

    axesHandle = axes( ...
        'Parent',figureHandle, ...
        'Position',[0.045 0.075 0.645 0.835]);

    plotEnvironment(axesHandle,environment,cfg);
end

% Remove any remaining map title created during goal selection.
title(axesHandle,'');

set(0,'CurrentFigure',figureHandle);
set(figureHandle,'CurrentAxes',axesHandle);
end

function handles = initializeLocal( ...
    figureHandle,axesHandle,pose,goal,scan, ...
    command,dwaDebug,cfg,globalPath, ...
    localTarget,pathInfo,slamState)

hold(axesHandle,'on');

handles.figure = figureHandle;
handles.axes = axesHandle;

%% Main-map graphics
handles.globalPath = plot( ...
    axesHandle,globalPath(:,1),globalPath(:,2), ...
    '--','Color',[0.05 0.35 0.95], ...
    'LineWidth',2.1);

handles.actualTrajectory = plot( ...
    axesHandle,nan,nan, ...
    '-','Color',[0.85 0.10 0.10], ...
    'LineWidth',1.55);

handles.goal = plot( ...
    axesHandle,goal(1),goal(2), ...
    'r*','MarkerSize',22,'LineWidth',2.8);

handles.localTarget = plot( ...
    axesHandle,localTarget(1),localTarget(2), ...
    'mo','MarkerFaceColor','m','MarkerSize',7);

handles.projectedPoint = plot( ...
    axesHandle,pathInfo.projectedPoint(1), ...
    pathInfo.projectedPoint(2), ...
    'co','MarkerFaceColor','c','MarkerSize',5);

handles.lidarRays = plot( ...
    axesHandle,nan,nan, ...
    'Color',cfg.visualization.lidarRayColor, ...
    'LineWidth',0.35);

handles.lidarHits = plot( ...
    axesHandle,nan,nan,'.', ...
    'Color',cfg.visualization.lidarHitColor, ...
    'MarkerSize',6);

handles.predictionDots = plot( ...
    axesHandle,nan,nan, ...
    'LineStyle','none','Marker','.', ...
    'Color',[0.65 0.20 0.70], ...
    'MarkerSize',4);

handles.robot = drawRobot( ...
    axesHandle,pose,cfg,[]);

%% Fixed top heading panel
handles.headerAxes = axes( ...
    'Parent',figureHandle, ...
    'Position',[0.045 0.928 0.935 0.055], ...
    'Color',[0.97 0.99 0.97], ...
    'XLim',[0 1],'YLim',[0 1], ...
    'XTick',[],'YTick',[], ...
    'Box','on');

handles.headerText = text( ...
    handles.headerAxes,0.5,0.5, ...
    'Hybrid A* + DWA + 360° LiDAR + Live SLAM Navigation', ...
    'Units','normalized', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',[0.00 0.35 0.08], ...
    'Interpreter','none');

%% SLAM panel: upper-right
handles.slamAxes = axes( ...
    'Parent',figureHandle, ...
    'Position',[0.725 0.515 0.255 0.395]);

mapRGB = occupancyRgbLocal(slamState);

handles.slamImage = image( ...
    handles.slamAxes, ...
    [0 cfg.environment.worldWidth], ...
    [0 cfg.environment.worldHeight], ...
    mapRGB);

set(handles.slamAxes,'YDir','normal');
axis(handles.slamAxes,'equal');
axis(handles.slamAxes,[ ...
    0 cfg.environment.worldWidth ...
    0 cfg.environment.worldHeight]);
box(handles.slamAxes,'on');
grid(handles.slamAxes,'on');
hold(handles.slamAxes,'on');

handles.slamPath = plot( ...
    handles.slamAxes,globalPath(:,1),globalPath(:,2), ...
    '--','Color',[0.05 0.35 0.95], ...
    'LineWidth',1.0);

handles.slamTrajectory = plot( ...
    handles.slamAxes, ...
    slamState.trajectory(:,1), ...
    slamState.trajectory(:,2), ...
    'Color',[0.85 0.10 0.10], ...
    'LineWidth',1.1);

handles.slamPose = plot( ...
    handles.slamAxes, ...
    slamState.estimatedPose(1), ...
    slamState.estimatedPose(2), ...
    '^','Color',[0.00 0.25 0.90], ...
    'MarkerFaceColor',[0.00 0.45 1.00], ...
    'MarkerSize',7, ...
    'LineWidth',1.1);

handles.slamGoal = plot( ...
    handles.slamAxes,goal(1),goal(2), ...
    'r*','MarkerSize',12,'LineWidth',1.5);

title(handles.slamAxes, ...
    'SLAM — Live Occupancy Map', ...
    'FontSize',11,'FontWeight','bold');

xlabel(handles.slamAxes,'X (m)');
ylabel(handles.slamAxes,'Y (m)');

%% Dedicated lower-right information panel
handles.infoAxes = axes( ...
    'Parent',figureHandle, ...
    'Position',[0.725 0.075 0.255 0.395], ...
    'Color',[0.985 0.985 0.985], ...
    'XLim',[0 1],'YLim',[0 1], ...
    'XTick',[],'YTick',[], ...
    'Box','on');

handles.modeText = text( ...
    handles.infoAxes,0.04,0.965,'', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',[0.00 0.30 0.08], ...
    'Interpreter','none');

handles.infoText = text( ...
    handles.infoAxes,0.04,0.875,'', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',9.8, ...
    'FontWeight','bold', ...
    'Color',[0.08 0.08 0.08], ...
    'Interpreter','none');

handles.legendText = text( ...
    handles.infoAxes,0.04,0.245, ...
    sprintf([ ...
    'MAP LABELS\n' ...
    'Blue dashed: A* route\n' ...
    'Red solid: robot trajectory\n' ...
    'Magenta: look-ahead target\n' ...
    'Cyan: projected path point\n' ...
    'Green rays: LiDAR\n' ...
    'Blue triangle: SLAM robot pose\n' ...
    'Red star: selected goal']), ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',8.6, ...
    'Color',[0.12 0.12 0.12], ...
    'Interpreter','none');

handles.finalStatusText = text( ...
    handles.infoAxes,0.5,0.035,'', ...
    'Units','normalized', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Color',[0.85 0.05 0.05], ...
    'Interpreter','none');

handles = updateLocal( ...
    handles,pose,goal,scan,[],command,0, ...
    dwaDebug,cfg,[],globalPath,localTarget, ...
    pathInfo,slamState,'');
end

function handles = updateLocal( ...
    handles,pose,goal,scan,trajectoryHistory, ...
    command,simulationTime,dwaDebug,cfg, ...
    predictedTrajectory,globalPath,localTarget, ...
    pathInfo,slamState,statusMessage)

%% Update map graphics
set(handles.globalPath, ...
    'XData',globalPath(:,1), ...
    'YData',globalPath(:,2), ...
    'Visible',onOffLocal(cfg.path.showGlobalPath));

set(handles.goal,'XData',goal(1),'YData',goal(2));

set(handles.localTarget, ...
    'XData',localTarget(1), ...
    'YData',localTarget(2));

set(handles.projectedPoint, ...
    'XData',pathInfo.projectedPoint(1), ...
    'YData',pathInfo.projectedPoint(2));

numberOfRays = numel(scan.ranges);
rayX = nan(1,3*numberOfRays);
rayY = nan(1,3*numberOfRays);

for rayIndex = 1:numberOfRays
    dataIndex = 3*(rayIndex-1)+1;

    rayX(dataIndex:dataIndex+2) = [ ...
        pose(1),scan.hitPoints(rayIndex,1),nan];

    rayY(dataIndex:dataIndex+2) = [ ...
        pose(2),scan.hitPoints(rayIndex,2),nan];
end

set(handles.lidarRays,'XData',rayX,'YData',rayY);

hitPoints = scan.hitPoints(scan.hitMask,:);

if isempty(hitPoints)
    set(handles.lidarHits,'XData',nan,'YData',nan);
else
    set(handles.lidarHits, ...
        'XData',hitPoints(:,1), ...
        'YData',hitPoints(:,2));
end

if isempty(trajectoryHistory)
    set(handles.actualTrajectory,'XData',nan,'YData',nan);
else
    set(handles.actualTrajectory, ...
        'XData',trajectoryHistory(:,1), ...
        'YData',trajectoryHistory(:,2));
end

if isempty(predictedTrajectory) || ...
        ~cfg.visualization.showLocalPredictionDots
    set(handles.predictionDots,'XData',nan,'YData',nan);
else
    set(handles.predictionDots, ...
        'XData',predictedTrajectory(:,1), ...
        'YData',predictedTrajectory(:,2));
end

handles.robot = drawRobot( ...
    handles.axes,pose,cfg,handles.robot);

%% Calculate displayed values
distanceToGoal = norm(pose(1:2)'-goal);

leftWheelVelocity = ...
    (command(1)-command(2)*cfg.robot.wheelBase/2) / ...
    cfg.robot.wheelRadius;

rightWheelVelocity = ...
    (command(1)+command(2)*cfg.robot.wheelBase/2) / ...
    cfg.robot.wheelRadius;

clearance = fieldOrLocal( ...
    dwaDebug,'minimumClearance',min(scan.ranges));

candidateCount = fieldOrLocal( ...
    dwaDebug,'validCandidateCount',0);

replanCount = fieldOrLocal( ...
    dwaDebug,'replanCount',0);

if fieldOrLocal(dwaDebug,'terminalMode',false)
    navigationMode = 'TERMINAL DOCKING';
elseif fieldOrLocal(dwaDebug,'recoveryActive',false)
    navigationMode = 'LOCAL RECOVERY';
else
    navigationMode = 'A* + ROUTE-LOCK DWA TRACKING';
end

set(handles.modeText,'String',navigationMode);

information = sprintf([ ...
    'Time: %.1f s\n' ...
    'Goal distance: %.2f m\n' ...
    'Path progress: %.1f %%\n' ...
    'Cross-track error: %.3f m\n' ...
    'Correction angle: %.1f deg\n' ...
    'Look-ahead: %.2f m\n' ...
    'Linear velocity: %.2f m/s\n' ...
    'Angular velocity: %.2f rad/s\n' ...
    'Left wheel: %.2f rad/s\n' ...
    'Right wheel: %.2f rad/s\n' ...
    'Predicted clearance: %.2f m\n' ...
    'Valid DWA candidates: %d\n' ...
    'Replans: %d\n' ...
    'SLAM explored: %.1f %%'], ...
    simulationTime,distanceToGoal, ...
    100*pathInfo.progressFraction, ...
    pathInfo.crossTrackError, ...
    pathInfo.correctionAngle*180/pi, ...
    pathInfo.lookAheadDistance, ...
    command(1),command(2), ...
    leftWheelVelocity,rightWheelVelocity, ...
    clearance,candidateCount,replanCount, ...
    100*slamState.exploredFraction);

set(handles.infoText,'String',information);

if isempty(statusMessage)
    set(handles.finalStatusText,'String','');
    set(handles.headerText, ...
        'String', ...
        'Hybrid A* + DWA + 360° LiDAR + Live SLAM Navigation', ...
        'Color',[0.00 0.35 0.08]);
else
    set(handles.finalStatusText, ...
        'String',statusMessage);

    set(handles.headerText, ...
        'String',statusMessage, ...
        'Color',[0.85 0.05 0.05]);
end

%% Update SLAM panel
set(handles.slamImage, ...
    'CData',occupancyRgbLocal(slamState));

set(handles.slamPath, ...
    'XData',globalPath(:,1), ...
    'YData',globalPath(:,2));

set(handles.slamTrajectory, ...
    'XData',slamState.trajectory(:,1), ...
    'YData',slamState.trajectory(:,2));

set(handles.slamPose, ...
    'XData',slamState.estimatedPose(1), ...
    'YData',slamState.estimatedPose(2));

set(handles.slamGoal, ...
    'XData',goal(1),'YData',goal(2));
end

function mapRGB = occupancyRgbLocal(slamState)

probability = slamState.probability;
grayValue = 1-probability;
mapRGB = repmat(grayValue,[1 1 3]);

unknownMask = ~slamState.observed;

for channel = 1:3
    channelData = mapRGB(:,:,channel);
    channelData(unknownMask) = 0.58;
    mapRGB(:,:,channel) = channelData;
end
end

function valid = handlesValidLocal(handles)

required = { ...
    'figure','axes','globalPath','actualTrajectory', ...
    'goal','localTarget','projectedPoint','lidarRays', ...
    'lidarHits','predictionDots','robot', ...
    'headerAxes','headerText','slamAxes','slamImage', ...
    'slamPath','slamTrajectory','slamPose','slamGoal', ...
    'infoAxes','modeText','infoText','legendText', ...
    'finalStatusText'};

valid = isstruct(handles);

if ~valid
    return;
end

for index = 1:numel(required)
    if ~isfield(handles,required{index})
        valid = false;
        return;
    end
end

valid = ...
    validHandleLocal(handles.figure,'figure') && ...
    validHandleLocal(handles.axes,'axes') && ...
    validHandleLocal(handles.globalPath,'line') && ...
    validHandleLocal(handles.actualTrajectory,'line') && ...
    validHandleLocal(handles.goal,'line') && ...
    validHandleLocal(handles.localTarget,'line') && ...
    validHandleLocal(handles.projectedPoint,'line') && ...
    validHandleLocal(handles.lidarRays,'line') && ...
    validHandleLocal(handles.lidarHits,'line') && ...
    validHandleLocal(handles.predictionDots,'line') && ...
    validHandleLocal(handles.headerAxes,'axes') && ...
    validHandleLocal(handles.headerText,'text') && ...
    validHandleLocal(handles.slamAxes,'axes') && ...
    validHandleLocal(handles.slamImage,'image') && ...
    validHandleLocal(handles.slamPath,'line') && ...
    validHandleLocal(handles.slamTrajectory,'line') && ...
    validHandleLocal(handles.slamPose,'line') && ...
    validHandleLocal(handles.slamGoal,'line') && ...
    validHandleLocal(handles.infoAxes,'axes') && ...
    validHandleLocal(handles.modeText,'text') && ...
    validHandleLocal(handles.infoText,'text') && ...
    validHandleLocal(handles.legendText,'text') && ...
    validHandleLocal(handles.finalStatusText,'text') && ...
    robotValidLocal(handles.robot);
end

function valid = robotValidLocal(robot)

fields = {'body','leftWheel','rightWheel','heading','center'};
valid = isstruct(robot);

if ~valid
    return;
end

for index = 1:numel(fields)
    if ~isfield(robot,fields{index}) || ...
            ~validHandleLocal(robot.(fields{index}),'')
        valid = false;
        return;
    end
end
end

function valid = validHandleLocal(handleValue,expectedType)

valid = false;

try
    if isempty(handleValue) || ~ishandle(handleValue)
        return;
    end

    if isempty(expectedType)
        valid = true;
    else
        valid = strcmpi(get(handleValue,'Type'),expectedType);
    end
catch
    valid = false;
end
end

function deleteDynamicLocal(handles)

if ~isstruct(handles)
    return;
end

fields = { ...
    'globalPath','actualTrajectory','goal','localTarget', ...
    'projectedPoint','lidarRays','lidarHits', ...
    'predictionDots','headerAxes','slamAxes','infoAxes'};

for index = 1:numel(fields)
    if isfield(handles,fields{index})
        safeDeleteLocal(handles.(fields{index}));
    end
end

if isfield(handles,'robot') && isstruct(handles.robot)
    robotFields = {'body','leftWheel','rightWheel','heading','center'};

    for index = 1:numel(robotFields)
        if isfield(handles.robot,robotFields{index})
            safeDeleteLocal(handles.robot.(robotFields{index}));
        end
    end
end
end

function safeDeleteLocal(handleValue)

try
    if ~isempty(handleValue) && ishandle(handleValue)
        delete(handleValue);
    end
catch
end
end

function value = fieldOrLocal(structure,fieldName,defaultValue)

if isstruct(structure) && isfield(structure,fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end

function textValue = onOffLocal(value)

if value
    textValue = 'on';
else
    textValue = 'off';
end
end
